version: '3.8'

services:
  recipe:
    image: iamsanuj/recipe:latest
    build:
      context: .
    ports:
      - "3000:3000"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
